import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ko_KR': {
          'greeting': '안녕하세요',
          'playstage': '플레이스테이지',
          'lang0': '한국어',
          'lang1': '영어',
          'lang2': '중국어',
          'terms_agree1': '귀하는 계정을 생성하거나 로그인 함으로써 18세 이상임을 증명하고\n 본사의 ',
          'terms_agree2': '서비스 이용약관',
          'terms_agree3': '과 ',
          'terms_agree4': '개인정보 처리방침',
          'terms_agree5': '에 동의함으로 간주합니다.',
          'continue_phone': '전화번호로 계속하기',
          'next': '다음',
          'input_phonenumber': '전화번호를 입력하세요',
          'input_phonenumber_detail':
              '위 주소로 인증코드르 전송합니다.\n전화번호는 인증 이외에 타 목적으로 사용되지 않습니다.',
          'input_auth_code': '인증코드를 입력하세요',
          'input_auth_code_detail': '의 번호로 코드가 발송되었습니다.\n시간이 다소 걸릴 수도 있습니다.',
          'iam': '나는',
          'no_change_within_30d': '30일 내에 변경이 불가합니다.',
          'find_tendency': '찾는 성향',
          'up_to_3': '최대 3개 선택 가능합니다.',
          'create_profile': '프로필을 생성하세요',
          'name': '이름',
          'input_name': '이름을 입력하세요.',
          'birthday': '생년월일',
          'about_me': '자기소개',
          'input_after_touch': '터치 후 입력하세요.',
          'complete_profile': '프로필을 완성하세요',
          'complete_after_desc': '나중에 완성하시려면 건너뛰기를 터치하세요.',
          'height': '신장',
          'body_type': '신체 유형',
          'language_spoken': '사용 언어',
          'drinking': '술',
          'smoking': '담배',
          'skip': '건너뛰기',
          'add_photo': '사진을 추가하세요',
          'add_photo_desc': '+키를 눌러 최소 사진 한 장을 추가하세요.',
          'photo_warning': '경고 : 다음 경우에 해당되는 사진은 모두 삭제됩니다.',
          'photo_warning_detail':
              '1. 나체이거나 나체에 가까운 사람의 사진\n2. 아이들과 함께 찍은 사진\n3. 선정적이거나 신성모독적인 사진\n4. 페티시 또는 성행위를 묘사하거나 연상시키는 사진\n5. 각종 성인용품의 사진',
          'camera': '카메라',
          'album': '앨범',
          'complete': '완료',
          'allow_location': '위치 액세스 권한 허용',
          'allow_location_desc': '해당 앱을 사용하기 위해 위치 권한 허용이 필요합니다.',
          'people': '피플',
          'check_auth_code': '인증코드를 확인해 주세요.',
          'try_again': '다시 시도해 주세요.',
          'detail': '상세',
          'feed': '피드',
          'tendency': '성향',
          'feed_detail': '피드 (상세)',
        },
        'en_US': {
          'greeting': 'Hello',
          'playstage': 'PlayStage',
          'lang0': 'Korean',
          'lang1': 'English',
          'lang2': 'Chinese',
          'terms_agree1':
              'By creating an account or signing in, you certify you are at least\n18 years old and agree to our ',
          'terms_agree2': 'Terms of Use',
          'terms_agree3': ' and ',
          'terms_agree4': 'Privacy Policy.',
          'terms_agree5': '',
        },
        'zh_Hans': {
          'greeting': 'Hello',
          'playstage': 'PlayStage',
          'lang0': '韩语',
          'lang1': '英语',
          'lang2': '中文',
          'terms_agree1': '点击注册或登录, 即表示你同意我们的',
          'terms_agree2': '服务条款.\n',
          'terms_agree3': '查看',
          'terms_agree4': '隐私政策',
          'terms_agree5': ', 了解我们如何处理你的数据.',
        }
      };
}
